# Generated by Django 4.2.24 on 2025-11-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("speciality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("hospital", models.CharField(max_length=200)),
                ("experience", models.IntegerField()),
                ("fees", models.IntegerField()),
                ("rating", models.FloatField()),
            ],
        ),
    ]
