# Generated by Django 4.2.24 on 2025-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="fees",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="contact",
            name="rating",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
