# Generated by Django 4.2.24 on 2025-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_fees_alter_contact_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_photos/"),
        ),
    ]
