# Generated by Django 4.2.24 on 2025-11-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
