# Generated by Django 4.2.24 on 2025-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_pharmacy_pharmacystock_medicine_pharmacies"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pharmacystock",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="pharmacies",
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="map_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacystock",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("painkiller", "Painkiller"),
                    ("antibiotic", "Antibiotic"),
                    ("allergy", "Allergy Relief"),
                    ("cold_flu", "Cold & Flu"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacystock",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="pharmacystock",
            name="stock",
        ),
    ]
