# Generated by Django 4.2.24 on 2025-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_alter_pharmacystock_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("painkiller", "Painkiller"),
                    ("antibiotic", "Antibiotic"),
                    ("allergy", "Allergy Relief"),
                    ("cold_flu", "Cold & Flu"),
                    ("digestive", "Digestive System"),
                    ("vitamin", "Vitamin / Supplement"),
                    ("heart", "Heart & Blood Pressure"),
                    ("skin", "Skin / Topical"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
