# Generated by Django 4.2.10 on 2025-11-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_gender_delete_appointment'),
    ]

    operations = [
    ]
