# Generated by Django 4.2.24 on 2025-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0012_auto_20251116_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="child_safe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicine",
            name="minimum_age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="medicine",
            name="pregnancy_safe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicine",
            name="requires_prescription",
            field=models.BooleanField(default=False),
        ),
    ]
