# Generated by Django 4.2.24 on 2025-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0015_appointmentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="preferred_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("09:00 AM", "09:00 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("02:00 PM", "02:00 PM"),
                    ("03:00 PM", "03:00 PM"),
                    ("04:00 PM", "04:00 PM"),
                    ("05:00 PM", "05:00 PM"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
