# Generated by Django 4.2.24 on 2025-11-22 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0016_appointmentrequest_preferred_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
